# Generated by Django 4.1.7 on 2023-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0002_remove_pgn_desc_remove_pgn_title'),
        ('authentication', '0004_alter_user_is_coach_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(to='pgn.pgn'),
        ),
    ]
