# Generated by Django 4.1.7 on 2023-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0002_remove_pgn_desc_remove_pgn_title'),
        ('authentication', '0005_user_my_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(blank=True, related_name='my_games_set', to='pgn.pgn'),
        ),
    ]
