# Generated by Django 4.1.7 on 2023-03-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0002_remove_pgn_desc_remove_pgn_title'),
        ('authentication', '0007_alter_user_my_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned',
            field=models.ManyToManyField(related_name='user_assigned', to='pgn.pgn'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='user_favorites', to='pgn.pgn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(related_name='user_mygames', to='pgn.pgn'),
        ),
    ]
