# Generated by Django 4.1.7 on 2023-03-28 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0010_auto_20230325_2124'),
        ('authentication', '0009_auto_20230325_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgnFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('pgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgn.pgn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorited',
            field=models.ManyToManyField(related_name='favorite_pgns', through='authentication.PgnFavorites', to='pgn.pgn'),
        ),
    ]
