# Generated by Django 4.1.7 on 2023-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='fen id')),
                ('fen', models.TextField(verbose_name='fen file')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
    ]
