# Generated by Django 4.1.7 on 2023-02-27 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgn', '0001_initial'),
        ('fen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('game_id', models.CharField(max_length=128)),
                ('fen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fen.fen')),
                ('pgn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgn.pgn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
