# Generated by Django 4.1.7 on 2023-02-28 01:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fen', '0002_remove_fen_desc_remove_fen_title'),
        ('pgn', '0002_remove_pgn_desc_remove_pgn_title'),
        ('comment', '0002_alter_comment_fen_id_alter_comment_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fen_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fen.fen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game_id',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pgn_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pgn.pgn'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
