# Generated by Django 4.1.7 on 2023-02-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
