# Generated by Django 4.1.7 on 2023-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='pgn id')),
                ('pgn', models.TextField(verbose_name='pgn file')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
    ]
