# Generated by Django 4.1.7 on 2023-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0002_remove_pgn_desc_remove_pgn_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgn',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='is favorite'),
        ),
    ]
