# Generated by Django 4.1.7 on 2023-03-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0003_pgn_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgn',
            name='is_favorite',
        ),
    ]
