# Generated by Django 4.1.7 on 2023-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0005_pgn_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgn',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='is favorite'),
        ),
    ]
