# Generated by Django 4.1.7 on 2023-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0006_alter_pgn_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgn',
            name='favorites_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
