# Generated by Django 4.1.7 on 2023-03-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0007_pgn_favorites_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgn',
            old_name='favorites_dict',
            new_name='favorited_dict',
        ),
    ]
