# Generated by Django 4.1.7 on 2023-03-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0008_rename_favorites_dict_pgn_favorited_dict'),
    ]

    operations = [
    ]
