# Generated by Django 4.1.7 on 2023-03-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgn', '0009_auto_20230325_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgn',
            name='is_favorite',
        )
    ]
